version: '3'
services:
  downloader:
     image: jrmcdonald/podcasts-downloader
     restart: always
     volumes:
      - app_data:/data
  app:
     image: jrmcdonald/podcasts-app
     restart: always
     environment: 
      - PODCAST_FILE_SOURCE=/data/audio/
     volumes:
      - app_data:/data
  proxy:
      image: jrmcdonald/podcasts-proxy
      restart: always
      depends_on:
        - app
      ports:
        - 80:80
        - 443:443
      volumes:
        - passwd_data:/etc/apache2
        - certs_data:/etc/letsencrypt
        - certs_www:/var/www/certbot
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - certs_data:/etc/letsencrypt
      - certs_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    

volumes:
  app_data:
  certs_data:
  certs_www:
  passwd_data: