version: '3'
services:
  downloader:
     image: jrmcdonald/podcasts/downloader
     restart: always
     volumes:
      - app_data:/data
  app:
     image: jrmcdonald/podcasts/app
     restart: always
     ports: 
      - 8080:8080
     volumes:
      - app_data:/data

volumes:
  app_data: