version: '3'
services:
  downloader:
     image: jrmcdonald/podcasts-downloader
     restart: always
     volumes:
      - app_data:/data
  app:
     image: jrmcdonald/podcasts-app
     restart: always
     environment: 
      - PODCAST_FILE_SOURCE=/data/audio/
     volumes:
      - app_data:/data
  proxy:
      image: jrmcdonald/podcasts-proxy
      restart: always
      depends_on:
        - app
      ports:
        - 80:80
        - 443:443
      volumes:
        - passwd_data:/etc/apache2
        - certs_data:/etc/letsencrypt/:ro

volumes:
  app_data:
  certs_data:
  passwd_data: