version: '3'
services:
  downloader:
     image: jrmcdonald/podcasts-downloader
     restart: always
     volumes:
      - app_data:/data
  app:
     image: jrmcdonald/podcasts-app
     restart: always
     environment: 
      - APP_FILE_SOURCE=/data/audio/
     ports: 
      - 80:8080
     volumes:
      - app_data:/data

volumes:
  app_data: